# Multi100 Project, Repeatable analysis
Analyst ID: DAA9C

## Paper: 
Paper ID: McDevitt_JournPoliEco_2014_yQeR

McDevitt, R.C. (2014). "A" Business by Any Other Name: Firm Name Choice as a Signal of Firm Quality. *Journal of Political Economy*, 122(4), 909-944.

## Claim: 
The average plumbing firm whose name begins with A or a number receives... more service complaints than other firms ...(p. 909.)

### First convert files from the original .dta (Stata) format into something I can read (.csv)
I did this one at a time, probably could have figured out a loop for all .dta files and convert them in one shot, but oh well

In [7]:
import pandas as pd

In [54]:
string = 'yelp_2013_users'
filename = string + '.dta'
filename

'yelp_2013_users.dta'

In [ ]:
data = pd.io.stata.read_stata(filename)

In [53]:
csv_filename = filename + '.csv'
data.to_csv(csv_filename)

### Find data
Paper claims 'the primary data for all plumbing firms...come(s) from a June 2008 download of the Web-based version of ReferenceUSA'. This data was not provided in the .zip file for download (p. 913, Section II. Data Description)

Additionally, 'the primary measure of firm quality...is the number of compliants filed against the firm with the Better Business Bureau...(which) comes from a June 2008 download of the BBB's website.' This data was also not provided in a raw form in the files available for download.

### File called 'final_data' appears to contain cleaned and summarized data
Number of records (2,293) in this file matches that in Table 2 in Online Appendex: **'Summary Statistics for Illinois Plumbing Firms'**

In [69]:
df_full = pd.read_csv('final_data.dta.csv')

In [70]:
df_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2293 entries, 0 to 2292
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           2293 non-null   int64
 1   firm_id              2293 non-null   object
 2   chicago              2293 non-null   float64
 3   complaints_2008      2293 non-null   float64
 4   num_names_2008       2293 non-null   float64
 5   emp_size             2293 non-null   float64
 6   ad_spending          2293 non-null   float64
 7   firm_age             2293 non-null   float64
 8   fixedfee             543 non-null    float64
 9   hourlyrate           543 non-null    float64
 10  emergency            728 non-null    float64
 11  multiple_names       2293 non-null   float64
 12  ad_spend_k           2293 non-null   float64
 13  first_A              2293 non-null   float64
 14  deflated_complaints  2293 non-null   float64
 15  has_fixed_fee        543 non-null    float64
 16  total_price          543 non-null    float64
 17  in_survey            2293 non-null   float64
 18  emergency_A          728 non-null    float64
 19  on_google            2293 non-null   float64
dtypes: float64(18), int64(1), object(1)
memory usage: 358.4+ KB

### Keep only the two columns I need

In [71]:
df = df_full[['complaints_2008','first_A']]

In [72]:
df

      complaints_2008  first_A
0                 0.0      0.0
1                 0.0      0.0
2                 1.0      0.0
3                 0.0      0.0
4                 0.0      0.0
...               ...      ...
2288              0.0      0.0
2289              6.0      1.0
2290              0.0      0.0
2291              3.0      1.0
2292              0.0      1.0

[2293 rows x 2 columns]

In [91]:
# first_A of 0 means firm name does NOT begin with A or a number
df['first_A'].value_counts()

0.0    1998
1.0     295
Name: first_A, dtype: int64

In [93]:
# Groupby name type, calculate summary metrics
df.groupby('first_A').agg(['count','mean','std','min','max'])

        complaints_2008
                  count      mean       std  min   max
first_A
0.0                1998  0.248248  2.055181  0.0  57.0
1.0                 295  1.338983  4.798704  0.0  43.0

In [94]:
# Save groupby df
grouped_df = df.groupby('first_A').agg(['count','mean','std','min','max'])

In [95]:
grouped_df['complaints_2008']['mean']

first_A
0.0    0.248248
1.0    1.338983
Name: mean, dtype: float64

In [97]:
# How much higher is the mean number of complaints for first_A = 1 (those beginning with A or number)?
# 1.33 / .248
grouped_df['complaints_2008']['mean'][1] / grouped_df['complaints_2008']['mean'][0]

5.393726079825041